config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :fall_detections
  resources :sugar_levels
  resources :blood_pressures
  resources :images
  get '/dashboard', to:'dashboard#index'

  root to: 'dashboard#index'

  get '/blood_pressure_data', to:'graph#blood_pressure_data', :defaults => { :format => 'json' }
  get '/sugar_level_data', to:'graph#sugar_level_data', :defaults => { :format => 'json' }

  get '/get_images_by_uuid', to:'images#get_images_by_uuid', :defaults => { :format => 'json'}
  get '/get_contacts_by_uuid', to:'contacts#get_contacts_by_uuid', :defaults => { :format => 'json'}

  post '/sugar_level', to: 'sugar_levels#create_by_uuid', :defaults => { :format => 'json' }
  post '/blood_pressure', to: 'blood_pressures#create_by_uuid', :defaults => { :format => 'json' }
  post '/fall_detection', to: 'fall_detections#create_by_uuid', :defaults => { :format => 'json' }
  devise_for :users

end

app/models/sugar_level.rb
class SugarLevel < ActiveRecord::Base
  belongs_to :user
end

app/controllers/sugar_levels_controller.rb
class SugarLevelsController < ApplicationController
  before_action :set_sugar_level, only: [:show, :edit, :update, :destroy]

  # GET /sugar_levels
  # GET /sugar_levels.json
  def index
    @sugar_levels = SugarLevel.where(user_id: current_user.id)
  end

  # GET /sugar_levels/1
  # GET /sugar_levels/1.json
  def show
  end

  # GET /sugar_levels/new
  def new
    @sugar_level = SugarLevel.new
  end

  # GET /sugar_levels/1/edit
  def edit
  end

  # POST /sugar_levels
  # POST /sugar_levels.json
  def create
    @sugar_level = SugarLevel.new(sugar_level_params)
    @sugar_level.user_id = current_user.id
    respond_to do |format|
      if @sugar_level.save
        format.html { redirect_to @sugar_level, notice: 'Sugar level was successfully created.' }
        format.json { render :show, status: :created, location: @sugar_level }
      else
        format.html { render :new }
        format.json { render json: @sugar_level.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_by_uuid
    @sugar_level = SugarLevel.new(sugar_level_params)
    uuid = params[:uuid]
    user = User.find_by_uuid(uuid)
    @sugar_level.user_id=user.id
    respond_to do |format|
      if @sugar_level.save
        format.html { redirect_to @sugar_level, notice: 'Sugar level was successfully created.' }
        format.json { render :show, status: :created, location: @sugar_level }
      else
        format.html { render :new }
        format.json { render json: @sugar_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sugar_levels/1
  # PATCH/PUT /sugar_levels/1.json
  def update
    @sugar_level.user_id = current_user.id
    respond_to do |format|
      if @sugar_level.update(sugar_level_params)
        format.html { redirect_to @sugar_level, notice: 'Sugar level was successfully updated.' }
        format.json { render :show, status: :ok, location: @sugar_level }
      else
        format.html { render :edit }
        format.json { render json: @sugar_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sugar_levels/1
  # DELETE /sugar_levels/1.json
  def destroy
    @sugar_level.destroy
    respond_to do |format|
      format.html { redirect_to sugar_levels_url, notice: 'Sugar level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sugar_level
      @sugar_level = SugarLevel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sugar_level_params
      params.require(:sugar_level).permit(:user_id, :mg_per_dl, :checkup_time)
    end
end

app/helpers/sugar_levels_helper.rb
module SugarLevelsHelper
end

app/views/sugar_levels/_form.html.erb
<%= form_for @sugar_level, :html => { :class => "form-horizontal sugar_level" } do |f| %>

  <% if @sugar_level.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@sugar_level.errors.count, "error") %> prohibited this sugar_level from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @sugar_level.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :mg_per_dl, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mg_per_dl, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mg_per_dl) %>
  </div>
  <div class="form-group">
    <%= f.label :checkup_time, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.datetime_select :checkup_time, :class => 'form-control' %>
    </div>
    <%=f.error_span(:checkup_time) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sugar_levels_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/sugar_levels/edit.html.erb
<%- model_class = SugarLevel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sugar_levels/index.html.erb
<%- model_class = SugarLevel -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:mg_per_dl) %></th>
      <th><%= model_class.human_attribute_name(:checkup_time) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sugar_levels.each do |sugar_level| %>
      <tr>
        <td><%= link_to sugar_level.id, sugar_level_path(sugar_level) %></td>
        <td><%= sugar_level.mg_per_dl %></td>
        <td><%= sugar_level.checkup_time %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sugar_level_path(sugar_level), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sugar_level_path(sugar_level),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sugar_level_path,
            :class => 'btn btn-primary' %>

app/views/sugar_levels/new.html.erb
<%- model_class = SugarLevel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sugar_levels/show.html.erb
<%- model_class = SugarLevel -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:mg_per_dl) %>:</strong></dt>
  <dd><%= @sugar_level.mg_per_dl %></dd>
  <dt><strong><%= model_class.human_attribute_name(:checkup_time) %>:</strong></dt>
  <dd><%= @sugar_level.checkup_time %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              sugar_levels_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sugar_level_path(@sugar_level), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sugar_level_path(@sugar_level),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>