config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :fall_detections
  resources :sugar_levels
  resources :blood_pressures
  resources :images
  get '/dashboard', to:'dashboard#index'

  root to: 'dashboard#index'

  get '/blood_pressure_data', to:'graph#blood_pressure_data', :defaults => { :format => 'json' }
  get '/sugar_level_data', to:'graph#sugar_level_data', :defaults => { :format => 'json' }

  get '/get_images_by_uuid', to:'images#get_images_by_uuid', :defaults => { :format => 'json'}
  get '/get_contacts_by_uuid', to:'contacts#get_contacts_by_uuid', :defaults => { :format => 'json'}

  post '/sugar_level', to: 'sugar_levels#create_by_uuid', :defaults => { :format => 'json' }
  post '/blood_pressure', to: 'blood_pressures#create_by_uuid', :defaults => { :format => 'json' }
  post '/fall_detection', to: 'fall_detections#create_by_uuid', :defaults => { :format => 'json' }
  devise_for :users

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :name, ImageUploader
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.where(user_id: current_user.id)
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user_id = current_user.id
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_images_by_uuid
    uuid = params[:uuid]
    user = User.where(uuid:  uuid)
    images = Image.where(user_id: user.ids)
    render json: images
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:user_id, :name)
    end

    def image_uuid_params
      params.require(:image).permit(:uu)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image, html: {multipart: true} do |f| %>
    <% if @image.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@image.errors.count, "error") %> prohibited this pet from being saved:</h2>

          <ul>
            <% @image.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.file_field :name %>
    </div>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/images/edit.html.erb
<h1 class="page-header">Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image, class: "btn btn-link"%> |
<%= link_to 'Back', images_path, class: "btn btn-link"  %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-header">Listing Images</h1>

<table class="table table-bordered table-striped">

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to image_tag(image.name.thumb.url), image %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Delete', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path, class: 'btn btn-link' %>

app/views/images/new.html.erb
<h1 class="page-header">New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path, class: "btn btn-link" %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <%= image_tag @image.name.detail.url %>
</p>

<%= link_to 'Edit', edit_image_path(@image), class: "btn btn-link" %> |
<%= link_to 'Back', images_path, class: "btn btn-link" %>