config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :fall_detections
  resources :sugar_levels
  resources :blood_pressures
  resources :images
  get '/dashboard', to:'dashboard#index'

  root to: 'dashboard#index'

  get '/blood_pressure_data', to:'graph#blood_pressure_data', :defaults => { :format => 'json' }
  get '/sugar_level_data', to:'graph#sugar_level_data', :defaults => { :format => 'json' }

  get '/get_images_by_uuid', to:'images#get_images_by_uuid', :defaults => { :format => 'json'}
  get '/get_contacts_by_uuid', to:'contacts#get_contacts_by_uuid', :defaults => { :format => 'json'}

  post '/sugar_level', to: 'sugar_levels#create_by_uuid', :defaults => { :format => 'json' }
  post '/blood_pressure', to: 'blood_pressures#create_by_uuid', :defaults => { :format => 'json' }
  post '/fall_detection', to: 'fall_detections#create_by_uuid', :defaults => { :format => 'json' }
  devise_for :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssestiveDomotics</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="panel-body">
<% if user_signed_in? %>
    <!-- sidebar -->
    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
      <ul class="nav">
        <li class="active"><%= link_to('Dashboard', root_path) %></li>
        <li><%= link_to('Manage Photos', images_path) %></li>
        <li><%= link_to('Blood Pressure Status', blood_pressures_path) %></li>
        <li><%= link_to('Sugar Level Status', sugar_levels_path) %></li>
        <li><%= link_to('Fall Detection', fall_detections_path) %></li>
        <li><%= link_to('Contacts', contacts_path) %></li>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
      </ul>
    </div>
<% end %>


<div class="col-xs-12 col-sm-9">
  <%= yield %>
</div>


</body>
</html>